### ISSUE TITLE
GPU calculation

### ISSUE THREAD

**Issue by Hyunseung-Kim** [mjwen/bondnet#2]
First of all, thank you for sharing your great research.

I have a question about GPU computation.

Does it right to set the bellow parameter to 0, if I want to use GPU for calculation?:

> In train_bde_disbritubed.py

```
    parser.add_argument(
        "--gpu", type=int, default=None, help="GPU index. None to use CPU."
    )
```

If I changed it like below:

```
    parser.add_argument(
        "--gpu", type=int, default=0, help="GPU index. None to use CPU."
    )
```

It makes errors, and the error messages are like below:
```
Traceback (most recent call last):
  File "C:/Users/Usr/PycharmProjects/bondnet-master/train_bde_distributed.py", line 496, in <module>
    main()
  File "C:/Users/Usr/PycharmProjects/bondnet-master/train_bde_distributed.py", line 492, in main
    main_worker(args.gpu, None, args)
  File "C:/Users/Usr/PycharmProjects/bondnet-master/train_bde_distributed.py", line 420, in main_worker
    optimizer, model, feature_names, train_loader, loss_func, metric, args.gpu
  File "C:/Users/Usr/PycharmProjects/bondnet-master/train_bde_distributed.py", line 174, in train
    pred = model(bg, feats, label["reaction"], norm_atom, norm_bond)
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Usr\PycharmProjects\bondnet-master\bondnet\model\gated_reaction_network.py", line 29, in forward
    feats = layer(graph, feats, norm_atom, norm_bond)
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Usr\PycharmProjects\bondnet-master\bondnet\layer\gatedconv.py", line 151, in forward
    g.nodes["atom"].data.update({"Ah": self.A(h), "Dh": self.D(h), "Eh": self.E(h)})
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\dgl\view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\dgl\heterograph.py", line 3997, in _set_n_repr
    ' same device.'.format(key, F.context(val), self.device))
dgl._ffi.base.DGLError: Cannot assign node feature "Ah" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.
```

**Comment by Hyunseung-Kim** [comment]
It seems that dgl has two version; one is for cpu computation and the other is for cuda computation.
